spring.application.name=Dilkush

spring.datasource.url=jdbc:postgresql://localhost:5432/digital_banking
spring.datasource.username=postgres
spring.datasource.password=D9890311645

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080